version: '3.8'
services:
  frontend:
    build: .
    ports:
      - '3001:3001'
    environment:
      - NEXT_PUBLIC_API_URL=http://host.docker.internal:3000
    volumes:
      - .:/app
    depends_on: []
